In [279]:
import numpy as np

from numpy.random import dirichlet as d
from numpy.random import multinomial as m
from numpy.random import choice as c

In [280]:
def draw_dir(a):
    return m(n=1, pvals=d(a, size=1)[0], size=1)

def draw_choice(a):
    z = a/np.sum(a)
    choice = c(['a', 'b', 'c'], p=z, size=1)[0]
    return np.array({'a':[1,0,0], 'b':[0,1,0], 'c':[0,0,1]}[choice])


In [281]:
sims = 10000
a = [1,2,3]

r_dir = np.zeros(shape=[sims, 3])
r_choice = np.zeros(shape=[sims, 3])
for i in range(sims):
    r_dir[i] = draw_dir(a)
    r_choice[i] = draw_choice(a)
    
print("dir:")    
print(np.mean(r_dir, axis=0))
print(np.var(r_dir, axis=0))
print("choice:")
print(np.mean(r_choice, axis=0))
print(np.var(r_choice, axis=0))

dir:
[0.1648 0.3307 0.5045]
[0.13764096 0.22133751 0.24997975]
choice:
[0.1702 0.3359 0.4939]
[0.14123196 0.22307119 0.24996279]


In [282]:
sims = 10000
a = [100,200,300]

r_dir = np.zeros(shape=[sims, 3])
r_choice = np.zeros(shape=[sims, 3])
for i in range(sims):
    r_dir[i] = draw_dir(a)
    r_choice[i] = draw_choice(a)
    
print("dir:")    
print(np.mean(r_dir, axis=0))
print(np.var(r_dir, axis=0))
print("choice:")
print(np.mean(r_choice, axis=0))
print(np.var(r_choice, axis=0))

dir:
[0.166  0.3427 0.4913]
[0.138444   0.22525671 0.24992431]
choice:
[0.1717 0.3229 0.5054]
[0.14221911 0.21863559 0.24997084]


In [283]:
def draw_dir_n(a, n):
    return m(n=n, pvals=d(a, size=1)[0], size=1)

In [284]:
sims = 10000
a = [1,2,3]

r_dir = np.zeros(shape=[sims, 3])
r_choice = np.zeros(shape=[sims, 3])
for i in range(sims):
    r_dir[i] = draw_dir_n(a, 10)
    r_choice[i] = draw_choice(a)
    
print("dir:")    
print(np.mean(r_dir, axis=0))
print(np.var(r_dir, axis=0))
print("choice:")
print(np.mean(r_choice, axis=0))
print(np.var(r_choice, axis=0))

dir:
[1.6671 3.3617 4.9712]
[3.19587759 5.04687311 5.66877056]
choice:
[0.1628 0.3289 0.5083]
[0.13629616 0.22072479 0.24993111]


In [285]:
np.mean(r_dir[:1000], axis=0)

array([1.671, 3.442, 4.887])

In [276]:
np.mean(r_choice, axis=0)

array([0.1645, 0.3326, 0.5029])